markdown: kramdown
kramdown:
  parse_block_html: true
theme: jekyll-theme-minimal
github: [metadata]

show_drafts         : true

collections:
    topics:
        label: Topics  
        output: true
        permalink: /topics/:path/
