theme: jekyll-theme-cayman
github: # [metadata]

remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme 

markdown: kramdown

kramdown:
  parse_block_html: true
    
show_drafts         : true

collections:
    topics:
        label: Topics  
        output: true
        permalink: /topics/:path/
