theme: jekyll-theme-cayman
github: # [metadata]

markdown: kramdown

kramdown:
  parse_block_html: true
    
show_drafts         : true

collections:
    topics:
        label: Topics  
        output: true
        permalink: /topics/:path/
